defaults:
  - _self_
  - dataset: cifar10
  - model: dino_vit_S14
  - override hydra/hydra_logging: rich_logger
  - override hydra/job_logging: rich_logger


split: "both"  # "train" | "test" | "both"


dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: false

  # params for hydra.utils.instantiate
  _target_: torch.utils.data.DataLoader
  _partial_: true


trainer:
  precision: "16-mixed"

  # params for hydra.utils.instantiate
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: 1
  logger: false


# sweep over combinations of datasets and models
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      dataset: 
        cifar10,
        cifar100,
        food101,
        cars,
        aircraft,
        dtd,
        pets,
        flowers,
        svhn,
        places365,
        amyloid_beta,
        blood_smear,
        cell_cycle,
        colon_polyps,
        colorectal_histology,
        heart_failure,
        liquid_based_cytology,
        patch_camelyon
      model:
        openclip_vit_B16,
        openclip_vit_L14,
        openclip_vit_H14,
        openclip_vit_g14,
        openclip_vit_G14,
        dino_vit_S14,        
        dino_vit_B14,
        dino_vit_L14,
        dino_vit_g14

  # disable hydra logging
  run:
    dir: ""
  sweep:
    dir: /tmp/$USER/multirun
  job:
    chdir: false
  output_subdir: null
  